name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        runtime: [wasmtime, wasmer]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup wasmer
        if: ${{ matrix.runtime }} == "wasmer"
        run: |
          curl https://get.wasmer.io -sSfL | bash
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Setup wasmtime
        if: ${{ matrix.runtime }} == "wasmtime"
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH

      - name: Build tests
        run: bash build.sh

      - name: Run tests
        run: bash test.sh tools/run-${{ matrix.runtime }}
